package service

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
	"unicode"

	"tools.bctechvibe.com/server/internal/modules/json-tools/models"
)

// JSONToGoStruct chuyển đổi JSON string thành Go Struct definition
func JSONToGoStruct(jsonStr string) (string, error) {
	var data interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return "", fmt.Errorf("không thể parse JSON: dữ liệu đầu vào không hợp lệ")
	}

	switch v := data.(type) {
	case map[string]interface{}:
		return generateStruct("AutoGenerated", v, 0), nil
	case []interface{}:
		if len(v) > 0 {
			if obj, ok := v[0].(map[string]interface{}); ok {
				return generateStruct("AutoGenerated", obj, 0), nil
			}
		}
		return "// Mảng không chứa object, không thể tạo struct.\n// Kiểu dữ liệu gốc: []interface{}", nil
	default:
		return "", fmt.Errorf("JSON phải là Object hoặc Array of Objects để chuyển thành Go Struct")
	}
}

// generateStruct đệ quy tạo struct definition
func generateStruct(name string, obj map[string]interface{}, depth int) string {
	var sb strings.Builder
	indent := strings.Repeat("\t", depth)

	sb.WriteString(fmt.Sprintf("%stype %s struct {\n", indent, name))

	// Sắp xếp keys theo alphabet cho dễ đọc
	keys := make([]string, 0, len(obj))
	for k := range obj {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var nestedStructs []string

	for _, key := range keys {
		value := obj[key]
		goFieldName := toGoFieldName(key)
		goType, nested := inferGoType(goFieldName, value, depth+1)

		sb.WriteString(fmt.Sprintf("%s\t%s %s `json:\"%s\"`\n", indent, goFieldName, goType, key))

		if nested != "" {
			nestedStructs = append(nestedStructs, nested)
		}
	}

	sb.WriteString(fmt.Sprintf("%s}\n", indent))

	// Thêm các nested struct phía sau
	for _, ns := range nestedStructs {
		sb.WriteString("\n")
		sb.WriteString(ns)
	}

	return sb.String()
}

// inferGoType suy luận Go type từ giá trị JSON
func inferGoType(fieldName string, value interface{}, depth int) (string, string) {
	if value == nil {
		return "interface{}", ""
	}

	switch v := value.(type) {
	case bool:
		return "bool", ""
	case float64:
		if v == float64(int64(v)) {
			return "int64", ""
		}
		return "float64", ""
	case string:
		return "string", ""
	case []interface{}:
		if len(v) == 0 {
			return "[]interface{}", ""
		}
		elemType, nested := inferGoType(fieldName, v[0], depth)
		return "[]" + elemType, nested
	case map[string]interface{}:
		structName := fieldName
		nested := generateStruct(structName, v, 0)
		return structName, nested
	default:
		return "interface{}", ""
	}
}

// toGoFieldName chuyển đổi JSON key thành Go field name hợp lệ
func toGoFieldName(key string) string {
	if key == "" {
		return "Field"
	}

	parts := splitFieldName(key)
	var result strings.Builder

	for _, part := range parts {
		if part == "" {
			continue
		}
		// Viết hoa chữ cái đầu
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		result.WriteString(string(runes))
	}

	name := result.String()
	if name == "" {
		return "Field"
	}

	// Xử lý các acronym phổ biến
	name = fixAcronyms(name)

	return name
}

// splitFieldName tách field name theo underscore, hyphen, hoặc camelCase
func splitFieldName(s string) []string {
	// Tách theo _ và -
	s = strings.ReplaceAll(s, "-", "_")
	parts := strings.Split(s, "_")

	var result []string
	for _, part := range parts {
		// Tách thêm theo camelCase
		subParts := splitCamelCase(part)
		result = append(result, subParts...)
	}

	return result
}

// splitCamelCase tách chuỗi camelCase thành các từ
func splitCamelCase(s string) []string {
	var parts []string
	var current strings.Builder

	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			parts = append(parts, current.String())
			current.Reset()
		}
		current.WriteRune(r)
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}

	return parts
}

// fixAcronyms sửa lại các acronym phổ biến (Id -> ID, Url -> URL, v.v.)
func fixAcronyms(s string) string {
	acronyms := map[string]string{
		"Id": "ID", "Url": "URL", "Uri": "URI",
		"Http": "HTTP", "Https": "HTTPS", "Ssh": "SSH",
		"Ip": "IP", "Dns": "DNS", "Ssl": "SSL", "Tls": "TLS",
		"Cpu": "CPU", "Ram": "RAM", "Os": "OS", "Api": "API",
		"Json": "JSON", "Xml": "XML", "Html": "HTML", "Css": "CSS",
		"Sql": "SQL", "Ttl": "TTL",
	}

	for from, to := range acronyms {
		if strings.HasSuffix(s, from) {
			s = s[:len(s)-len(from)] + to
		}
	}

	return s
}

// JSONToYAML chuyển đổi JSON string thành YAML format
func JSONToYAML(jsonStr string) (string, error) {
	var data interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return "", fmt.Errorf("không thể parse JSON: dữ liệu đầu vào không hợp lệ")
	}

	result := marshalYAML(data, 0)
	return strings.TrimRight(result, "\n"), nil
}

// marshalYAML đệ quy chuyển đổi interface{} thành YAML string
func marshalYAML(data interface{}, indent int) string {
	if data == nil {
		return "null\n"
	}

	prefix := strings.Repeat("  ", indent)

	switch v := data.(type) {
	case map[string]interface{}:
		if len(v) == 0 {
			return "{}\n"
		}

		// Sắp xếp keys
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		var sb strings.Builder
		for _, key := range keys {
			val := v[key]
			switch child := val.(type) {
			case map[string]interface{}, []interface{}:
				_ = child
				sb.WriteString(fmt.Sprintf("%s%s:\n", prefix, key))
				sb.WriteString(marshalYAML(val, indent+1))
			default:
				sb.WriteString(fmt.Sprintf("%s%s: %s", prefix, key, marshalYAMLScalar(val)))
			}
		}
		return sb.String()

	case []interface{}:
		if len(v) == 0 {
			return "[]\n"
		}
		var sb strings.Builder
		for _, item := range v {
			switch child := item.(type) {
			case map[string]interface{}:
				// Inline first key, rest indented
				keys := make([]string, 0, len(child))
				for k := range child {
					keys = append(keys, k)
				}
				sort.Strings(keys)

				if len(keys) > 0 {
					firstKey := keys[0]
					sb.WriteString(fmt.Sprintf("%s- %s: %s", prefix, firstKey, marshalYAMLScalar(child[firstKey])))
					for _, k := range keys[1:] {
						sb.WriteString(fmt.Sprintf("%s  %s: %s", prefix, k, marshalYAMLScalar(child[k])))
					}
				} else {
					sb.WriteString(fmt.Sprintf("%s- {}\n", prefix))
				}
			default:
				sb.WriteString(fmt.Sprintf("%s- %s", prefix, marshalYAMLScalar(item)))
			}
		}
		return sb.String()

	default:
		return marshalYAMLScalar(v)
	}
}

// marshalYAMLScalar chuyển đổi giá trị scalar thành YAML string
func marshalYAMLScalar(v interface{}) string {
	if v == nil {
		return "null\n"
	}
	switch val := v.(type) {
	case string:
		// Kiểm tra nếu string chứa ký tự đặc biệt cần quote
		if needsQuoting(val) {
			return fmt.Sprintf("\"%s\"\n", strings.ReplaceAll(val, "\"", "\\\""))
		}
		return val + "\n"
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d\n", int64(val))
		}
		return fmt.Sprintf("%g\n", val)
	case bool:
		if val {
			return "true\n"
		}
		return "false\n"
	default:
		return fmt.Sprintf("%v\n", val)
	}
}

// needsQuoting kiểm tra xem string có cần quote trong YAML không
func needsQuoting(s string) bool {
	if s == "" {
		return true
	}
	special := []string{":", "#", "[", "]", "{", "}", ",", "&", "*", "!", "|", ">", "'", "\"", "%", "@", "`"}
	for _, c := range special {
		if strings.Contains(s, c) {
			return true
		}
	}
	// Các giá trị YAML đặc biệt
	lower := strings.ToLower(s)
	reserved := []string{"true", "false", "null", "yes", "no", "on", "off"}
	for _, r := range reserved {
		if lower == r {
			return true
		}
	}
	return false
}

// ComputeDiff so sánh 2 JSON strings và trả về kết quả diff
func ComputeDiff(originalStr, modifiedStr string) (*models.DiffResponse, error) {
	var original, modified interface{}

	if err := json.Unmarshal([]byte(originalStr), &original); err != nil {
		return nil, fmt.Errorf("JSON gốc (Original) không hợp lệ")
	}
	if err := json.Unmarshal([]byte(modifiedStr), &modified); err != nil {
		return nil, fmt.Errorf("JSON chỉnh sửa (Modified) không hợp lệ")
	}

	leftFlat := flattenJSON(original, "")
	rightFlat := flattenJSON(modified, "")

	// Tập hợp tất cả keys
	allKeys := make(map[string]bool)
	for k := range leftFlat {
		allKeys[k] = true
	}
	for k := range rightFlat {
		allKeys[k] = true
	}

	var added, removed, modified_ []models.DiffEntry

	for key := range allKeys {
		leftVal, inLeft := leftFlat[key]
		rightVal, inRight := rightFlat[key]

		if inLeft && inRight {
			if !reflect.DeepEqual(leftVal, rightVal) {
				modified_ = append(modified_, models.DiffEntry{
					Key:      key,
					Type:     "modified",
					OldValue: leftVal,
					NewValue: rightVal,
				})
			}
		} else if inLeft && !inRight {
			removed = append(removed, models.DiffEntry{
				Key:   key,
				Type:  "removed",
				Value: leftVal,
			})
		} else {
			added = append(added, models.DiffEntry{
				Key:   key,
				Type:  "added",
				Value: rightVal,
			})
		}
	}

	// Sắp xếp theo key
	sort.Slice(added, func(i, j int) bool { return added[i].Key < added[j].Key })
	sort.Slice(removed, func(i, j int) bool { return removed[i].Key < removed[j].Key })
	sort.Slice(modified_, func(i, j int) bool { return modified_[i].Key < modified_[j].Key })

	return &models.DiffResponse{
		Added:    added,
		Removed:  removed,
		Modified: modified_,
		Summary: models.DiffSummary{
			TotalAdded:    len(added),
			TotalRemoved:  len(removed),
			TotalModified: len(modified_),
		},
	}, nil
}

// flattenJSON làm phẳng cấu trúc JSON lồng thành key → value map
func flattenJSON(data interface{}, prefix string) map[string]interface{} {
	result := make(map[string]interface{})

	switch v := data.(type) {
	case map[string]interface{}:
		if len(v) == 0 {
			key := prefix
			if key == "" {
				key = "(root)"
			}
			result[key] = map[string]interface{}{}
			return result
		}
		for k, val := range v {
			newKey := k
			if prefix != "" {
				newKey = prefix + "." + k
			}
			for fk, fv := range flattenJSON(val, newKey) {
				result[fk] = fv
			}
		}
	case []interface{}:
		if len(v) == 0 {
			key := prefix
			if key == "" {
				key = "(root)"
			}
			result[key] = []interface{}{}
			return result
		}
		for i, item := range v {
			newKey := fmt.Sprintf("[%d]", i)
			if prefix != "" {
				newKey = prefix + fmt.Sprintf("[%d]", i)
			}
			for fk, fv := range flattenJSON(item, newKey) {
				result[fk] = fv
			}
		}
	default:
		key := prefix
		if key == "" {
			key = "(root)"
		}
		result[key] = data
	}

	return result
}
