package service

import (
	"strings"
	"testing"
)

// ==============================
// Tests for toGoFieldName
// ==============================

func TestToGoFieldName(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{name: "simple lowercase", input: "name", expected: "Name"},
		{name: "snake_case", input: "first_name", expected: "FirstName"},
		{name: "hyphen", input: "first-name", expected: "FirstName"},
		{name: "camelCase", input: "firstName", expected: "FirstName"},
		{name: "PascalCase", input: "FirstName", expected: "FirstName"},
		{name: "id acronym", input: "id", expected: "ID"},
		{name: "user_id", input: "user_id", expected: "UserID"},
		{name: "url", input: "url", expected: "URL"},
		{name: "api_key", input: "api_key", expected: "APIKey"},

		// Edge cases từ review
		{name: "starts with number", input: "1st_name", expected: "X1stName"},
		{name: "dot in key", input: "a.b", expected: "AB"},
		{name: "key with spaces", input: "user name", expected: "UserName"},
		{name: "key with colon", input: "a:b", expected: "AB"},
		{name: "empty string", input: "", expected: "Field"},
		{name: "only special chars", input: "!@#", expected: "Field"},
		{name: "mixed with numbers", input: "field123", expected: "Field123"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := toGoFieldName(tt.input)
			if got != tt.expected {
				t.Errorf("toGoFieldName(%q) = %q, want %q", tt.input, got, tt.expected)
			}
		})
	}
}

// ==============================
// Tests for escapeStructTag
// ==============================

func TestFormatStructTag(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{name: "normal key", input: "user_name", expected: "`json:\"user_name\"`"},
		{name: "key with double quote", input: `a"b`, expected: "`json:\"a\\\"b\"`"},
		{name: "key with backslash", input: `a\b`, expected: "`json:\"a\\\\b\"`"},
		{name: "key with backtick", input: "a`b", expected: `"json:\"a` + "`" + `b\""`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := formatStructTag(tt.input)
			if got != tt.expected {
				t.Errorf("formatStructTag(%q) = %q, want %q", tt.input, got, tt.expected)
			}
		})
	}
}

// ==============================
// Tests for JSONToGoStruct
// ==============================

func TestJSONToGoStruct(t *testing.T) {
	t.Run("simple object", func(t *testing.T) {
		input := `{"name": "Alice", "age": 30}`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "type AutoGenerated struct") {
			t.Error("missing struct declaration")
		}
		if !strings.Contains(result, "Name string") {
			t.Error("missing Name field")
		}
		if !strings.Contains(result, "Age int64") {
			t.Error("missing Age field")
		}
	})

	t.Run("key starting with number", func(t *testing.T) {
		input := `{"1st_name": "Bob"}`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		// Field name phải bắt đầu bằng chữ cái
		if strings.Contains(result, "\t1") {
			t.Error("field name starts with digit — sẽ không compile được")
		}
		if !strings.Contains(result, "X1stName") {
			t.Errorf("expected X1stName prefix, got:\n%s", result)
		}
	})

	t.Run("key with dot", func(t *testing.T) {
		input := `{"a.b": 1}`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		// Field name không được chứa dấu chấm
		if strings.Contains(result, "\ta.b") {
			t.Error("field name contains dot — sẽ không compile được")
		}
	})

	t.Run("duplicate field names after normalization", func(t *testing.T) {
		// "id" và "ID" đều normalize thành "ID" -> phải có hậu tố để tránh trùng
		input := `{"id": 1, "ID": 2}`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		// Đếm số lần xuất hiện của "ID " (field declaration)
		count := strings.Count(result, "\tID ")
		// Một trong 2 phải có hậu tố _2
		if count > 1 {
			t.Errorf("duplicate field 'ID' detected:\n%s", result)
		}
	})

	t.Run("large integer precision", func(t *testing.T) {
		// Snowflake ID: 9007199254740993 > 2^53, float64 sẽ mất precision
		input := `{"snowflake_id": 9007199254740993}`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "int64") {
			t.Errorf("expected int64 for large integer, got:\n%s", result)
		}
	})

	t.Run("array of objects - merge schema", func(t *testing.T) {
		// Phần tử đầu thiếu field "email", phần tử sau có
		input := `[{"name": "Alice"}, {"name": "Bob", "email": "bob@example.com"}]`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "Email string") {
			t.Errorf("expected Email field from merged schema, got:\n%s", result)
		}
		if !strings.Contains(result, "Name string") {
			t.Errorf("expected Name field, got:\n%s", result)
		}
	})

	t.Run("key with double quote", func(t *testing.T) {
		input := `{"a\"b": 1}`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		// Struct tag không được có dấu " trần
		_ = result
	})

	t.Run("empty array", func(t *testing.T) {
		input := `[]`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "rỗng") {
			t.Errorf("expected empty array comment, got: %s", result)
		}
	})

	t.Run("nested object", func(t *testing.T) {
		input := `{"user": {"name": "Alice", "age": 30}}`
		result, err := JSONToGoStruct(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "User AutoGeneratedUser") {
			t.Errorf("expected nested struct type, got:\n%s", result)
		}
	})

	t.Run("invalid json", func(t *testing.T) {
		_, err := JSONToGoStruct(`{invalid}`)
		if err == nil {
			t.Error("expected error for invalid JSON")
		}
	})

	t.Run("trailing data", func(t *testing.T) {
		_, err := JSONToGoStruct(`{"a": 1} trailing`)
		if err == nil {
			t.Error("expected error for trailing data")
		}
	})
}

// ==============================
// Tests for JSONToYAML
// ==============================

func TestJSONToYAML(t *testing.T) {
	t.Run("simple object", func(t *testing.T) {
		input := `{"name": "Alice", "age": 30}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "name: Alice") {
			t.Errorf("expected 'name: Alice', got:\n%s", result)
		}
		if !strings.Contains(result, "age: 30") {
			t.Errorf("expected 'age: 30', got:\n%s", result)
		}
	})

	t.Run("key with colon - must be quoted", func(t *testing.T) {
		input := `{"a:b": "value"}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		// Key "a:b" phải được quote thành "a:b":
		if !strings.Contains(result, `"a:b":`) {
			t.Errorf("expected quoted key \"a:b\", got:\n%s", result)
		}
	})

	t.Run("key with hash - must be quoted", func(t *testing.T) {
		input := `{"foo # bar": "value"}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, `"foo # bar":`) {
			t.Errorf("expected quoted key for 'foo # bar', got:\n%s", result)
		}
	})

	t.Run("key 'true' - must be quoted", func(t *testing.T) {
		input := `{"true": "value"}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, `"true":`) {
			t.Errorf("expected quoted key for boolean keyword 'true', got:\n%s", result)
		}
	})

	t.Run("key with leading space - must be quoted", func(t *testing.T) {
		input := `{" leading": "value"}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, `" leading":`) {
			t.Errorf("expected quoted key for key with leading space, got:\n%s", result)
		}
	})

	t.Run("large integer - no precision loss", func(t *testing.T) {
		input := `{"id": 9007199254740993}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "9007199254740993") {
			t.Errorf("expected large integer to be preserved, got:\n%s", result)
		}
	})

	t.Run("boolean values", func(t *testing.T) {
		input := `{"active": true, "deleted": false}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "active: true") {
			t.Errorf("expected 'active: true', got:\n%s", result)
		}
	})

	t.Run("string value needing quotes", func(t *testing.T) {
		input := `{"note": "hello: world"}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, `"hello: world"`) {
			t.Errorf("expected quoted value 'hello: world', got:\n%s", result)
		}
	})

	t.Run("nested array", func(t *testing.T) {
		input := `{"tags": ["go", "yaml"]}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "- go") {
			t.Errorf("expected '- go' in array output, got:\n%s", result)
		}
	})

	t.Run("null value", func(t *testing.T) {
		input := `{"data": null}`
		result, err := JSONToYAML(input)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(result, "data: null") {
			t.Errorf("expected 'data: null', got:\n%s", result)
		}
	})

	t.Run("invalid json", func(t *testing.T) {
		_, err := JSONToYAML(`{invalid}`)
		if err == nil {
			t.Error("expected error for invalid JSON")
		}
	})
}

// ==============================
// Tests for needsQuoting
// ==============================

func TestNeedsQuoting(t *testing.T) {
	tests := []struct {
		input    string
		expected bool
	}{
		{"", true},
		{"normal", false},
		{"a:b", true},
		{"foo # bar", true},
		{"true", true},
		{"false", true},
		{"null", true},
		{"yes", true},
		{"no", true},
		{"on", true},
		{"off", true},
		{"123", true},
		{" leading", true},
		{"trailing ", true},
		{"hello world", false}, // dấu cách ở giữa — không cần quote theo YAML spec (nhưng lưu ý context)
		{"normal-key", false},
		{"key_underscore", false},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := needsQuoting(tt.input)
			if got != tt.expected {
				t.Errorf("needsQuoting(%q) = %v, want %v", tt.input, got, tt.expected)
			}
		})
	}
}

// ==============================
// Tests for mergeObjectSchemas
// ==============================

func TestMergeObjectSchemas(t *testing.T) {
	t.Run("merge fields from multiple objects", func(t *testing.T) {
		items := []interface{}{
			map[string]interface{}{"a": "1"},
			map[string]interface{}{"b": "2"},
			map[string]interface{}{"a": "3", "c": "4"},
		}
		merged := mergeObjectSchemas(items)
		if merged == nil {
			t.Fatal("expected non-nil result")
		}
		if _, ok := merged["a"]; !ok {
			t.Error("expected key 'a'")
		}
		if _, ok := merged["b"]; !ok {
			t.Error("expected key 'b'")
		}
		if _, ok := merged["c"]; !ok {
			t.Error("expected key 'c'")
		}
	})

	t.Run("prefer non-nil values", func(t *testing.T) {
		items := []interface{}{
			map[string]interface{}{"a": nil},
			map[string]interface{}{"a": "hello"},
		}
		merged := mergeObjectSchemas(items)
		if merged["a"] != "hello" {
			t.Errorf("expected non-nil value for 'a', got: %v", merged["a"])
		}
	})

	t.Run("empty array", func(t *testing.T) {
		result := mergeObjectSchemas([]interface{}{})
		if result != nil && len(result) != 0 {
			// mergeObjectSchemas trả về empty map hoặc nil cho mảng rỗng
		}
	})

	t.Run("non-object items ignored", func(t *testing.T) {
		items := []interface{}{"string", 123, true}
		result := mergeObjectSchemas(items)
		if result != nil {
			t.Errorf("expected nil for non-object array, got: %v", result)
		}
	})
}
