package service

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// JSONToGoStruct chuyển đổi JSON string thành Go Struct definition
func JSONToGoStruct(jsonStr string) (string, error) {
	var data interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return "", fmt.Errorf("không thể parse JSON: dữ liệu đầu vào không hợp lệ")
	}

	switch v := data.(type) {
	case map[string]interface{}:
		return generateStruct("", "AutoGenerated", v, 0), nil
	case []interface{}:
		if len(v) > 0 {
			if obj, ok := v[0].(map[string]interface{}); ok {
				return generateStruct("", "AutoGenerated", obj, 0), nil
			}
			// Hỗ trợ mảng primitive
			elemType, _ := inferGoType("", "Item", v[0], 0)
			return fmt.Sprintf("// type AutoGenerated = []%s\nvar Data []%s", elemType, elemType), nil
		}
		return "// Mảng rỗng, không thể xác định kiểu dữ liệu.", nil
	default:
		return "", fmt.Errorf("JSON phải là Object hoặc Array of Objects để chuyển thành Go Struct")
	}
}

// generateStruct đệ quy tạo struct definition
func generateStruct(parentName, name string, obj map[string]interface{}, depth int) string {
	var sb strings.Builder
	indent := strings.Repeat("\t", depth)

	structName := parentName + name
	sb.WriteString(fmt.Sprintf("%stype %s struct {\n", indent, structName))

	// Sắp xếp keys theo alphabet cho dễ đọc
	keys := make([]string, 0, len(obj))
	for k := range obj {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var nestedStructs []string

	for _, key := range keys {
		value := obj[key]
		goFieldName := toGoFieldName(key)
		goType, nested := inferGoType(structName, goFieldName, value, depth+1)

		sb.WriteString(fmt.Sprintf("%s\t%s %s `json:\"%s\"`\n", indent, goFieldName, goType, key))

		if nested != "" {
			nestedStructs = append(nestedStructs, nested)
		}
	}

	sb.WriteString(fmt.Sprintf("%s}\n", indent))

	// Thêm các nested struct phía sau
	for _, ns := range nestedStructs {
		sb.WriteString("\n")
		sb.WriteString(ns)
	}

	return sb.String()
}

// inferGoType suy luận Go type từ giá trị JSON
func inferGoType(parentName, fieldName string, value interface{}, depth int) (string, string) {
	if value == nil {
		return "interface{}", ""
	}

	switch v := value.(type) {
	case bool:
		return "bool", ""
	case float64:
		if v == float64(int64(v)) {
			return "int64", ""
		}
		return "float64", ""
	case string:
		return "string", ""
	case []interface{}:
		if len(v) == 0 {
			return "[]interface{}", ""
		}
		
		// Scan toàn bộ mảng để kiểm tra tính đồng nhất của kiểu dữ liệu
		var firstType string
		var firstNested string
		var isMixed bool
		
		for _, item := range v {
			if item == nil {
				continue
			}
			t, n := inferGoType(parentName, fieldName, item, depth)
			if firstType == "" {
				firstType = t
				firstNested = n
			} else if t != firstType {
				isMixed = true
				break
			}
		}
		
		if isMixed || firstType == "" {
			return "[]interface{}", ""
		}
		
		return "[]" + firstType, firstNested
	case map[string]interface{}:
		nested := generateStruct(parentName, fieldName, v, 0)
		return parentName + fieldName, nested
	default:
		return "interface{}", ""
	}
}

// toGoFieldName chuyển đổi JSON key thành Go field name hợp lệ
func toGoFieldName(key string) string {
	if key == "" {
		return "Field"
	}

	parts := splitFieldName(key)
	var result strings.Builder

	for _, part := range parts {
		if part == "" {
			continue
		}
		// Viết hoa chữ cái đầu
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		result.WriteString(string(runes))
	}

	name := result.String()
	if name == "" {
		return "Field"
	}

	// Xử lý các acronym phổ biến
	name = fixAcronyms(name)

	return name
}

// splitFieldName tách field name theo underscore, hyphen, hoặc camelCase
func splitFieldName(s string) []string {
	// Tách theo _ và -
	s = strings.ReplaceAll(s, "-", "_")
	parts := strings.Split(s, "_")

	var result []string
	for _, part := range parts {
		// Tách thêm theo camelCase
		subParts := splitCamelCase(part)
		result = append(result, subParts...)
	}

	return result
}

// splitCamelCase tách chuỗi camelCase thành các từ
func splitCamelCase(s string) []string {
	var parts []string
	var current strings.Builder

	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			parts = append(parts, current.String())
			current.Reset()
		}
		current.WriteRune(r)
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}

	return parts
}

// fixAcronyms sửa lại các acronym phổ biến (Id -> ID, Url -> URL, v.v.)
func fixAcronyms(s string) string {
	acronyms := map[string]string{
		"Id": "ID", "Url": "URL", "Uri": "URI",
		"Http": "HTTP", "Https": "HTTPS", "Ssh": "SSH",
		"Ip": "IP", "Dns": "DNS", "Ssl": "SSL", "Tls": "TLS",
		"Cpu": "CPU", "Ram": "RAM", "Os": "OS", "Api": "API",
		"Json": "JSON", "Xml": "XML", "Html": "HTML", "Css": "CSS",
		"Sql": "SQL", "Ttl": "TTL",
	}

	// Sắp xếp acronyms theo độ dài giảm dần để tránh replace "Https" thành "HTTPS" rồi lại dính "Http"
	type pair struct{ from, to string }
	var sorted []pair
	for k, v := range acronyms {
		sorted = append(sorted, pair{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool {
		return len(sorted[i].from) > len(sorted[j].from)
	})

	for _, p := range sorted {
		if s == p.from {
			return p.to
		}

		// Tìm vị trí của acronym trong chuỗi
		pos := 0
		for {
			idx := strings.Index(s[pos:], p.from)
			if idx == -1 {
				break
			}
			matchPos := pos + idx
			pos = matchPos + len(p.from)

			// Kiểm tra ranh giới: 
			// 1. Phải bắt đầu bằng chữ cái viết hoa (đã đảm bảo vì p.from là PascalCase)
			// 2. Ký tự tiếp theo phải là VIẾT HOA hoặc kết thúc chuỗi
			if len(s) == pos || unicode.IsUpper(rune(s[pos])) {
				s = s[:matchPos] + p.to + s[pos:]
				// Cập nhật lại pos sau khi replace
				pos = matchPos + len(p.to)
			}
		}
	}

	return s
}

// JSONToYAML chuyển đổi JSON string thành YAML format
func JSONToYAML(jsonStr string) (string, error) {
	var data interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return "", fmt.Errorf("không thể parse JSON: dữ liệu đầu vào không hợp lệ")
	}

	result := marshalYAML(data, 0)
	return strings.TrimRight(result, "\n"), nil
}

// marshalYAML đệ quy chuyển đổi interface{} thành YAML string
func marshalYAML(data interface{}, indent int) string {
	if data == nil {
		return "null\n"
	}

	prefix := strings.Repeat("  ", indent)

	switch v := data.(type) {
	case map[string]interface{}:
		if len(v) == 0 {
			return "{}\n"
		}

		// Sắp xếp keys
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		var sb strings.Builder
		for _, key := range keys {
			val := v[key]
			switch child := val.(type) {
			case map[string]interface{}, []interface{}:
				_ = child
				sb.WriteString(fmt.Sprintf("%s%s:\n", prefix, key))
				sb.WriteString(marshalYAML(val, indent+1))
			default:
				sb.WriteString(fmt.Sprintf("%s%s: %s", prefix, key, marshalYAMLScalar(val)))
			}
		}
		return sb.String()

	case []interface{}:
		if len(v) == 0 {
			return "[]\n"
		}
		var sb strings.Builder
		for _, item := range v {
			switch child := item.(type) {
			case map[string]interface{}, []interface{}:
				res := marshalYAML(child, indent+1)
				// Chỉ trim dòng đầu tiên để gán dấu "-", các dòng sau giữ nguyên indentation
				lines := strings.SplitN(res, "\n", 2)
				if len(lines) > 0 {
					firstLine := strings.TrimLeft(lines[0], " ")
					sb.WriteString(fmt.Sprintf("%s- %s\n", prefix, firstLine))
					if len(lines) > 1 && strings.TrimSpace(lines[1]) != "" {
						sb.WriteString(lines[1])
					}
				}
			default:
				sb.WriteString(fmt.Sprintf("%s- %s", prefix, marshalYAMLScalar(item)))
			}
		}
		return sb.String()

	default:
		return marshalYAMLScalar(v)
	}
}

// marshalYAMLScalar chuyển đổi giá trị scalar thành YAML string
func marshalYAMLScalar(v interface{}) string {
	if v == nil {
		return "null\n"
	}
	switch val := v.(type) {
	case string:
		// Kiểm tra nếu string chứa ký tự đặc biệt cần quote
		if needsQuoting(val) {
			// Thoát chuỗi đầy đủ: \, ", \n, \r, \t
			escaped := strings.ReplaceAll(val, "\\", "\\\\")
			escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
			escaped = strings.ReplaceAll(escaped, "\n", "\\n")
			escaped = strings.ReplaceAll(escaped, "\r", "\\r")
			escaped = strings.ReplaceAll(escaped, "\t", "\\t")
			return fmt.Sprintf("\"%s\"\n", escaped)
		}
		return val + "\n"
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d\n", int64(val))
		}
		return fmt.Sprintf("%g\n", val)
	case bool:
		if val {
			return "true\n"
		}
		return "false\n"
	default:
		return fmt.Sprintf("%v\n", val)
	}
}

// needsQuoting kiểm tra xem string có cần quote trong YAML không
func needsQuoting(s string) bool {
	if s == "" {
		return true
	}
	special := []string{":", "#", "[", "]", "{", "}", ",", "&", "*", "!", "|", ">", "'", "\"", "%", "@", "`"}
	for _, c := range special {
		if strings.Contains(s, c) {
			return true
		}
	}
	// Các giá trị YAML đặc biệt
	// Nếu string chứa leading/trailing whitespace
	if strings.TrimSpace(s) != s {
		return true
	}
	// Nếu string trông giống số hoặc boolean
	if _, err := strconv.ParseFloat(s, 64); err == nil {
		return true
	}
	lower := strings.ToLower(s)
	reserved := []string{"true", "false", "null", "yes", "no", "on", "off"}
	for _, r := range reserved {
		if lower == r {
			return true
		}
	}
	return false
}

