package service

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// decodeWithUseNumber dùng chung cho cả 2 hàm convert để đảm bảo số lớn không mất precision
func decodeWithUseNumber(jsonStr string) (interface{}, error) {
	dec := json.NewDecoder(strings.NewReader(jsonStr))
	dec.UseNumber()
	var data interface{}
	if err := dec.Decode(&data); err != nil {
		return nil, fmt.Errorf("không thể parse JSON: dữ liệu đầu vào không hợp lệ")
	}
	
	// Cẩn thận với trailing JSON token (vd: {"a":1} {"b":2})
	var dummy json.RawMessage
	if err := dec.Decode(&dummy); err != io.EOF {
		return nil, fmt.Errorf("không thể parse JSON: có dữ liệu thừa sau khi kết thúc JSON")
	}
	
	return data, nil
}

// JSONToGoStruct chuyển đổi JSON string thành Go Struct definition
func JSONToGoStruct(jsonStr string) (string, error) {
	data, err := decodeWithUseNumber(jsonStr)
	if err != nil {
		return "", err
	}

	switch v := data.(type) {
	case map[string]interface{}:
		return generateStruct("", "AutoGenerated", v, 0), nil
	case []interface{}:
		if len(v) > 0 {
			// Merge schema từ toàn bộ objects trong mảng, không chỉ lấy phần tử đầu
			merged := mergeObjectSchemas(v)
			if merged != nil {
				return generateStruct("", "AutoGenerated", merged, 0), nil
			}
			// Hỗ trợ mảng primitive
			elemType, _ := inferGoType("", "Item", v[0], 0)
			return fmt.Sprintf("// type AutoGenerated = []%s\nvar Data []%s", elemType, elemType), nil
		}
		return "// Mảng rỗng, không thể xác định kiểu dữ liệu.", nil
	default:
		return "", fmt.Errorf("JSON phải là Object hoặc Array of Objects để chuyển thành Go Struct")
	}
}

// mergeObjectSchemas gộp schema từ toàn bộ object trong một mảng để không bỏ sót field
func mergeObjectSchemas(items []interface{}) map[string]interface{} {
	merged := make(map[string]interface{})
	hasObj := false
	for _, item := range items {
		obj, ok := item.(map[string]interface{})
		if !ok {
			continue
		}
		hasObj = true
		for k, v := range obj {
			// Ưu tiên giữ giá trị không nil để suy luận kiểu chính xác hơn
			if existing, exists := merged[k]; !exists || existing == nil {
				merged[k] = v
			}
		}
	}
	if !hasObj {
		return nil
	}
	return merged
}

// generateStruct đệ quy tạo struct definition
func generateStruct(parentName, name string, obj map[string]interface{}, depth int) string {
	var sb strings.Builder
	indent := strings.Repeat("\t", depth)

	structName := parentName + name
	sb.WriteString(fmt.Sprintf("%stype %s struct {\n", indent, structName))

	// Sắp xếp keys theo alphabet cho dễ đọc
	keys := make([]string, 0, len(obj))
	for k := range obj {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var nestedStructs []string

	// usedNames theo dõi các field name đã dùng để giải quyết trùng lặp
	usedNames := make(map[string]int)

	for _, key := range keys {
		value := obj[key]
		goFieldName := toGoFieldName(key)

		// Giải quyết trùng lặp: nếu field name đã tồn tại, thêm hậu tố số
		if count, exists := usedNames[goFieldName]; exists {
			usedNames[goFieldName] = count + 1
			goFieldName = fmt.Sprintf("%s_%d", goFieldName, count+1)
		} else {
			usedNames[goFieldName] = 1
		}

		goType, nested := inferGoType(structName, goFieldName, value, depth+1)

		// Format struct tag, hỗ trợ bảo toàn hoàn toàn backtick bằng interpreted string literal
		tagStr := formatStructTag(key)
		sb.WriteString(fmt.Sprintf("%s\t%s %s %s\n", indent, goFieldName, goType, tagStr))

		if nested != "" {
			nestedStructs = append(nestedStructs, nested)
		}
	}

	sb.WriteString(fmt.Sprintf("%s}\n", indent))

	// Thêm các nested struct phía sau
	for _, ns := range nestedStructs {
		sb.WriteString("\n")
		sb.WriteString(ns)
	}

	return sb.String()
}

// formatStructTag tạo ra chuỗi struct tag hoàn chỉnh cho Go.
// Mặc định sử dụng raw string literal (`json:"..."`), nhưng nếu key chứa backtick,
// sẽ chuyển sang dùng interpreted string literal ("json:\"...\"") để bảo toàn nguyên vẹn giá trị key.
func formatStructTag(key string) string {
	// Escape backslash và double quote để struct tag parser (dùng strconv.Unquote) hiểu đúng
	escapedKey := strings.ReplaceAll(key, `\`, `\\`)
	escapedKey = strings.ReplaceAll(escapedKey, `"`, `\"`)
	tagValue := `json:"` + escapedKey + `"`

	if strings.Contains(tagValue, "`") {
		// Dùng interpreted string literal ("json:\"...\"")
		return strconv.Quote(tagValue)
	}

	// Dùng raw string literal
	return "`" + tagValue + "`"
}

// inferGoType suy luận Go type từ giá trị JSON
func inferGoType(parentName, fieldName string, value interface{}, depth int) (string, string) {
	if value == nil {
		return "interface{}", ""
	}

	switch v := value.(type) {
	case bool:
		return "bool", ""
	case json.Number:
		// Dùng UseNumber nên number sẽ là json.Number, không bị float64 precision loss
		// Thử parse về int64 trước, nếu không được thì float64
		if _, err := v.Int64(); err == nil {
			return "int64", ""
		}
		return "float64", ""
	case float64:
		// Fallback nếu value không qua UseNumber (nested context)
		if v == float64(int64(v)) {
			return "int64", ""
		}
		return "float64", ""
	case string:
		return "string", ""
	case []interface{}:
		if len(v) == 0 {
			return "[]interface{}", ""
		}

		// Với array of objects: merge schema toàn bộ phần tử
		mergedObj := mergeObjectSchemas(v)
		if mergedObj != nil {
			nested := generateStruct(parentName, fieldName, mergedObj, 0)
			return "[]" + parentName + fieldName, nested
		}

		// Scan toàn bộ mảng để kiểm tra tính đồng nhất của kiểu dữ liệu
		var firstType string
		var firstNested string
		var isMixed bool

		for _, item := range v {
			if item == nil {
				continue
			}
			t, n := inferGoType(parentName, fieldName, item, depth)
			if firstType == "" {
				firstType = t
				firstNested = n
			} else if t != firstType {
				isMixed = true
				break
			}
		}

		if isMixed || firstType == "" {
			return "[]interface{}", ""
		}

		return "[]" + firstType, firstNested
	case map[string]interface{}:
		nested := generateStruct(parentName, fieldName, v, 0)
		return parentName + fieldName, nested
	default:
		return "interface{}", ""
	}
}

// toGoFieldName chuyển đổi JSON key thành Go field name hợp lệ
func toGoFieldName(key string) string {
	if key == "" {
		return "Field"
	}

	parts := splitFieldName(key)
	var result strings.Builder

	for _, part := range parts {
		if part == "" {
			continue
		}
		// Lọc bỏ ký tự không hợp lệ trong identifier Go (chỉ giữ chữ, số, _)
		cleaned := filterIdentifierRunes(part)
		if cleaned == "" {
			continue
		}
		// Viết hoa chữ cái đầu
		runes := []rune(cleaned)
		runes[0] = unicode.ToUpper(runes[0])
		result.WriteString(string(runes))
	}

	name := result.String()
	if name == "" {
		return "Field"
	}

	// Nếu bắt đầu bằng số, thêm tiền tố X để tạo identifier hợp lệ
	if unicode.IsDigit([]rune(name)[0]) {
		name = "X" + name
	}

	// Xử lý các acronym phổ biến
	name = fixAcronyms(name)

	return name
}

// filterIdentifierRunes loại bỏ ký tự không hợp lệ trong Go identifier
// Go identifier chỉ chứa: chữ cái Unicode, số Unicode, dấu gạch dưới
func filterIdentifierRunes(s string) string {
	var sb strings.Builder
	for i, r := range s {
		if unicode.IsLetter(r) || r == '_' || (i > 0 && unicode.IsDigit(r)) {
			sb.WriteRune(r)
		} else if unicode.IsDigit(r) && i == 0 {
			// Giữ số ở đầu để sau này thêm tiền tố X
			sb.WriteRune(r)
		}
	}
	return sb.String()
}

// splitFieldName tách field name theo underscore, hyphen, hoặc camelCase
func splitFieldName(s string) []string {
	// Tách theo _ và -
	s = strings.ReplaceAll(s, "-", "_")
	// Tách theo ký tự đặc biệt phổ biến (chấm, dấu cách, v.v.)
	for _, sep := range []string{".", " ", ":", "/", "@", "#", "!", "?", "(", ")", "[", "]", "{", "}", "+"} {
		s = strings.ReplaceAll(s, sep, "_")
	}
	parts := strings.Split(s, "_")

	var result []string
	for _, part := range parts {
		if part == "" {
			continue
		}
		// Tách thêm theo camelCase
		subParts := splitCamelCase(part)
		result = append(result, subParts...)
	}

	return result
}

// splitCamelCase tách chuỗi camelCase thành các từ
func splitCamelCase(s string) []string {
	var parts []string
	var current strings.Builder

	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			parts = append(parts, current.String())
			current.Reset()
		}
		current.WriteRune(r)
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}

	return parts
}

// fixAcronyms sửa lại các acronym phổ biến (Id -> ID, Url -> URL, v.v.)
func fixAcronyms(s string) string {
	acronyms := map[string]string{
		"Id": "ID", "Url": "URL", "Uri": "URI",
		"Http": "HTTP", "Https": "HTTPS", "Ssh": "SSH",
		"Ip": "IP", "Dns": "DNS", "Ssl": "SSL", "Tls": "TLS",
		"Cpu": "CPU", "Ram": "RAM", "Os": "OS", "Api": "API",
		"Json": "JSON", "Xml": "XML", "Html": "HTML", "Css": "CSS",
		"Sql": "SQL", "Ttl": "TTL",
	}

	// Sắp xếp acronyms theo độ dài giảm dần để tránh replace "Https" thành "HTTPS" rồi lại dính "Http"
	type pair struct{ from, to string }
	var sorted []pair
	for k, v := range acronyms {
		sorted = append(sorted, pair{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool {
		return len(sorted[i].from) > len(sorted[j].from)
	})

	for _, p := range sorted {
		if s == p.from {
			return p.to
		}

		// Tìm vị trí của acronym trong chuỗi
		pos := 0
		for {
			idx := strings.Index(s[pos:], p.from)
			if idx == -1 {
				break
			}
			matchPos := pos + idx
			pos = matchPos + len(p.from)

			// Kiểm tra ranh giới:
			// 1. Phải bắt đầu bằng chữ cái viết hoa (đã đảm bảo vì p.from là PascalCase)
			// 2. Ký tự tiếp theo phải là VIẾT HOA hoặc kết thúc chuỗi
			if len(s) == pos || unicode.IsUpper(rune(s[pos])) {
				s = s[:matchPos] + p.to + s[pos:]
				// Cập nhật lại pos sau khi replace
				pos = matchPos + len(p.to)
			}
		}
	}

	return s
}

// JSONToYAML chuyển đổi JSON string thành YAML format
func JSONToYAML(jsonStr string) (string, error) {
	data, err := decodeWithUseNumber(jsonStr)
	if err != nil {
		return "", err
	}

	result := marshalYAML(data, 0)
	return strings.TrimRight(result, "\n"), nil
}

// marshalYAML đệ quy chuyển đổi interface{} thành YAML string
func marshalYAML(data interface{}, indent int) string {
	if data == nil {
		return "null\n"
	}

	prefix := strings.Repeat("  ", indent)

	switch v := data.(type) {
	case map[string]interface{}:
		if len(v) == 0 {
			return "{}\n"
		}

		// Sắp xếp keys
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		var sb strings.Builder
		for _, key := range keys {
			val := v[key]
			// Quote key nếu cần thiết (cùng logic với scalar strings)
			renderedKey := marshalYAMLKey(key)
			switch child := val.(type) {
			case map[string]interface{}, []interface{}:
				_ = child
				sb.WriteString(fmt.Sprintf("%s%s:\n", prefix, renderedKey))
				sb.WriteString(marshalYAML(val, indent+1))
			default:
				sb.WriteString(fmt.Sprintf("%s%s: %s", prefix, renderedKey, marshalYAMLScalar(val)))
			}
		}
		return sb.String()

	case []interface{}:
		if len(v) == 0 {
			return "[]\n"
		}
		var sb strings.Builder
		for _, item := range v {
			switch child := item.(type) {
			case map[string]interface{}, []interface{}:
				res := marshalYAML(child, indent+1)
				// Chỉ trim dòng đầu tiên để gán dấu "-", các dòng sau giữ nguyên indentation
				lines := strings.SplitN(res, "\n", 2)
				if len(lines) > 0 {
					firstLine := strings.TrimLeft(lines[0], " ")
					sb.WriteString(fmt.Sprintf("%s- %s\n", prefix, firstLine))
					if len(lines) > 1 && strings.TrimSpace(lines[1]) != "" {
						sb.WriteString(lines[1])
					}
				}
			default:
				sb.WriteString(fmt.Sprintf("%s- %s", prefix, marshalYAMLScalar(item)))
			}
		}
		return sb.String()

	default:
		return marshalYAMLScalar(v)
	}
}

// marshalYAMLKey render key trong YAML mapping, có quote nếu cần thiết
func marshalYAMLKey(key string) string {
	if needsQuoting(key) {
		escaped := strings.ReplaceAll(key, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		escaped = strings.ReplaceAll(escaped, "\n", `\n`)
		escaped = strings.ReplaceAll(escaped, "\r", `\r`)
		escaped = strings.ReplaceAll(escaped, "\t", `\t`)
		return fmt.Sprintf(`"%s"`, escaped)
	}
	return key
}

// marshalYAMLScalar chuyển đổi giá trị scalar thành YAML string
func marshalYAMLScalar(v interface{}) string {
	if v == nil {
		return "null\n"
	}
	switch val := v.(type) {
	case string:
		// Kiểm tra nếu string chứa ký tự đặc biệt cần quote
		if needsQuoting(val) {
			// Thoát chuỗi đầy đủ: \, ", \n, \r, \t
			escaped := strings.ReplaceAll(val, "\\", "\\\\")
			escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
			escaped = strings.ReplaceAll(escaped, "\n", "\\n")
			escaped = strings.ReplaceAll(escaped, "\r", "\\r")
			escaped = strings.ReplaceAll(escaped, "\t", "\\t")
			return fmt.Sprintf("\"%s\"\n", escaped)
		}
		return val + "\n"
	case json.Number:
		// Giữ nguyên json.Number dưới dạng string để không mất precision
		return val.String() + "\n"
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d\n", int64(val))
		}
		return fmt.Sprintf("%g\n", val)
	case bool:
		if val {
			return "true\n"
		}
		return "false\n"
	default:
		return fmt.Sprintf("%v\n", val)
	}
}

// needsQuoting kiểm tra xem string có cần quote trong YAML không
func needsQuoting(s string) bool {
	if s == "" {
		return true
	}
	special := []string{":", "#", "[", "]", "{", "}", ",", "&", "*", "!", "|", ">", "'", "\"", "%", "@", "`"}
	for _, c := range special {
		if strings.Contains(s, c) {
			return true
		}
	}
	// Nếu string chứa leading/trailing whitespace
	if strings.TrimSpace(s) != s {
		return true
	}
	// Nếu chứa newline
	if strings.ContainsAny(s, "\n\r\t") {
		return true
	}
	// Nếu string trông giống số hoặc boolean
	if _, err := strconv.ParseFloat(s, 64); err == nil {
		return true
	}
	lower := strings.ToLower(s)
	reserved := []string{"true", "false", "null", "yes", "no", "on", "off"}
	for _, r := range reserved {
		if lower == r {
			return true
		}
	}
	return false
}
