/*
===============================================
    GEOGRAPHIC UTILITIES FUNCTIONS
    Các hàm xử lý dữ liệu quốc gia / vị trí địa lý
=================================================
*/


/**
 * Chuyển tên quốc gia (English name) → mã quốc gia ISO 3166-1 alpha-2
 * Dùng để hiển thị cờ, map, API geo, CDN, v.v.
 *
 * Ví dụ:
 * "Vietnam"        → "vn"
 * "United States"  → "us"
 * "Japan"          → "jp"
 *
*/
// Mapping đầy đủ ~240 Quốc gia và Lãnh thổ (ISO 3166-1 alpha-2)
export function getCountryCode(countryName) {

    const countryMap = {
        "Afghanistan": "af",
        "Aland Islands": "ax",
        "Albania": "al",
        "Algeria": "dz",
        "American Samoa": "as",
        "Andorra": "ad",
        "Angola": "ao",
        "Anguilla": "ai",
        "Antarctica": "aq",
        "Antigua and Barbuda": "ag",
        "Argentina": "ar",
        "Armenia": "am",
        "Aruba": "aw",
        "Australia": "au",
        "Austria": "at",
        "Azerbaijan": "az",
        "Bahamas": "bs",
        "Bahrain": "bh",
        "Bangladesh": "bd",
        "Barbados": "bb",
        "Belarus": "by",
        "Belgium": "be",
        "Belize": "bz",
        "Benin": "bj",
        "Bermuda": "bm",
        "Bhutan": "bt",
        "Bolivia": "bo",
        "Bonaire, Sint Eustatius and Saba": "bq",
        "Bosnia and Herzegovina": "ba",
        "Botswana": "bw",
        "Bouvet Island": "bv",
        "Brazil": "br",
        "British Indian Ocean Territory": "io",
        "Brunei Darussalam": "bn",
        "Bulgaria": "bg",
        "Burkina Faso": "bf",
        "Burundi": "bi",
        "Cambodia": "kh",
        "Cameroon": "cm",
        "Canada": "ca",
        "Cape Verde": "cv",
        "Cayman Islands": "ky",
        "Central African Republic": "cf",
        "Chad": "td",
        "Chile": "cl",
        "China": "cn",
        "Christmas Island": "cx",
        "Cocos (Keeling) Islands": "cc",
        "Colombia": "co",
        "Comoros": "km",
        "Congo": "cg",
        "Congo, Democratic Republic of the Congo": "cd",
        "Congo, The Democratic Republic of the": "cd",
        "Cook Islands": "ck",
        "Costa Rica": "cr",
        "Cote D'Ivoire": "ci",
        "Croatia": "hr",
        "Cuba": "cu",
        "Curacao": "cw",
        "Cyprus": "cy",
        "Czech Republic": "cz",
        "Denmark": "dk",
        "Djibouti": "dj",
        "Dominica": "dm",
        "Dominican Republic": "do",
        "Ecuador": "ec",
        "Egypt": "eg",
        "El Salvador": "sv",
        "Equatorial Guinea": "gq",
        "Eritrea": "er",
        "Estonia": "ee",
        "Ethiopia": "et",
        "Falkland Islands (Malvinas)": "fk",
        "Faroe Islands": "fo",
        "Fiji": "fj",
        "Finland": "fi",
        "France": "fr",
        "French Guiana": "gf",
        "French Polynesia": "pf",
        "French Southern Territories": "tf",
        "Gabon": "ga",
        "Gambia": "gm",
        "Georgia": "ge",
        "Germany": "de",
        "Ghana": "gh",
        "Gibraltar": "gi",
        "Greece": "gr",
        "Greenland": "gl",
        "Grenada": "gd",
        "Guadeloupe": "gp",
        "Guam": "gu",
        "Guatemala": "gt",
        "Guernsey": "gg",
        "Guinea": "gn",
        "Guinea-Bissau": "gw",
        "Guyana": "gy",
        "Haiti": "ht",
        "Heard Island and Mcdonald Islands": "hm",
        "Holy See (Vatican City State)": "va",
        "Honduras": "hn",
        "Hong Kong": "hk",
        "Hungary": "hu",
        "Iceland": "is",
        "India": "in",
        "Indonesia": "id",
        "Iran, Islamic Republic of": "ir",
        "Iraq": "iq",
        "Ireland": "ie",
        "Isle of Man": "im",
        "Israel": "il",
        "Italy": "it",
        "Jamaica": "jm",
        "Japan": "jp",
        "Jersey": "je",
        "Jordan": "jo",
        "Kazakhstan": "kz",
        "Kenya": "ke",
        "Kiribati": "ki",
        "Korea, Democratic People's Republic of": "kp",
        "Korea, Republic of": "kr",
        "South Korea": "kr",
        "Kosovo": "xk",
        "Kuwait": "kw",
        "Kyrgyzstan": "kg",
        "Lao People's Democratic Republic": "la",
        "Latvia": "lv",
        "Lebanon": "lb",
        "Lesotho": "ls",
        "Liberia": "lr",
        "Libyan Arab Jamahiriya": "ly",
        "Liechtenstein": "li",
        "Lithuania": "lt",
        "Luxembourg": "lu",
        "Macao": "mo",
        "Macedonia, the Former Yugoslav Republic of": "mk",
        "North Macedonia": "mk",
        "Madagascar": "mg",
        "Malawi": "mw",
        "Malaysia": "my",
        "Maldives": "mv",
        "Mali": "ml",
        "Malta": "mt",
        "Marshall Islands": "mh",
        "Martinique": "mq",
        "Mauritania": "mr",
        "Mauritius": "mu",
        "Mayotte": "yt",
        "Mexico": "mx",
        "Micronesia, Federated States of": "fm",
        "Moldova, Republic of": "md",
        "Monaco": "mc",
        "Mongolia": "mn",
        "Montenegro": "me",
        "Montserrat": "ms",
        "Morocco": "ma",
        "Mozambique": "mz",
        "Myanmar": "mm",
        "Namibia": "na",
        "Nauru": "nr",
        "Nepal": "np",
        "Netherlands": "nl",
        "Netherlands Antilles": "an",
        "New Caledonia": "nc",
        "New Zealand": "nz",
        "Nicaragua": "ni",
        "Niger": "ne",
        "Nigeria": "ng",
        "Niue": "nu",
        "Norfolk Island": "nf",
        "Northern Mariana Islands": "mp",
        "Norway": "no",
        "Oman": "om",
        "Pakistan": "pk",
        "Palau": "pw",
        "Palestinian Territory, Occupied": "ps",
        "Panama": "pa",
        "Papua New Guinea": "pg",
        "Paraguay": "py",
        "Peru": "pe",
        "Philippines": "ph",
        "Pitcairn": "pn",
        "Poland": "pl",
        "Portugal": "pt",
        "Puerto Rico": "pr",
        "Qatar": "qa",
        "Reunion": "re",
        "Romania": "ro",
        "Russian Federation": "ru",
        "Russia": "ru",
        "Rwanda": "rw",
        "Saint Barthelemy": "bl",
        "Saint Helena": "sh",
        "Saint Kitts and Nevis": "kn",
        "Saint Lucia": "lc",
        "Saint Martin": "mf",
        "Saint Pierre and Miquelon": "pm",
        "Saint Vincent and the Grenadines": "vc",
        "Samoa": "ws",
        "San Marino": "sm",
        "Sao Tome and Principe": "st",
        "Saudi Arabia": "sa",
        "Senegal": "sn",
        "Serbia": "rs",
        "Serbia and Montenegro": "cs",
        "Seychelles": "sc",
        "Sierra Leone": "sl",
        "Singapore": "sg",
        "Sint Maarten": "sx",
        "Slovakia": "sk",
        "Slovenia": "si",
        "Solomon Islands": "sb",
        "Somalia": "so",
        "South Africa": "za",
        "South Georgia and the South Sandwich Islands": "gs",
        "South Sudan": "ss",
        "Spain": "es",
        "Sri Lanka": "lk",
        "Sudan": "sd",
        "Suriname": "sr",
        "Svalbard and Jan Mayen": "sj",
        "Swaziland": "sz",
        "Eswatini": "sz",
        "Sweden": "se",
        "Switzerland": "ch",
        "Syrian Arab Republic": "sy",
        "Syria": "sy",
        "Taiwan, Province of China": "tw",
        "Taiwan": "tw",
        "Tajikistan": "tj",
        "Tanzania, United Republic of": "tz",
        "Thailand": "th",
        "Timor-Leste": "tl",
        "Togo": "tg",
        "Tokelau": "tk",
        "Tonga": "to",
        "Trinidad and Tobago": "tt",
        "Tunisia": "tn",
        "Turkey": "tr",
        "Turkmenistan": "tm",
        "Turks and Caicos Islands": "tc",
        "Tuvalu": "tv",
        "Uganda": "ug",
        "Ukraine": "ua",
        "United Arab Emirates": "ae",
        "United Kingdom": "gb",
        "United States": "us",
        "United States Minor Outlying Islands": "um",
        "Uruguay": "uy",
        "Uzbekistan": "uz",
        "Vanuatu": "vu",
        "Venezuela": "ve",
        "Vietnam": "vn",
        "Viet Nam": "vn",
        "Virgin Islands, British": "vg",
        "Virgin Islands, U.s.": "vi",
        "Wallis and Futuna": "wf",
        "Western Sahara": "eh",
        "Yemen": "ye",
        "Zambia": "zm",
        "Zimbabwe": "zw"
    };

    //Trả về mã ISO hoặc chuỗi rỗng nếu không có
    return countryMap[countryName] || "";
}


/**
 * Tạo HTML hiển thị cờ quốc gia từ country code
 * Sử dụng CDN của flagcdn.com
 *
 * Nếu ảnh load lỗi → tự động ẩn
 *
 * Ví dụ:
 * "vn" → <img src=".../vn.png">
 *
 * @param {string} countryCode - ISO code (vd: vn, us, jp)
 * @returns {string} HTML img tag
 */
export function getCountryFlag(countryCode) {

    if (!countryCode) return "";

    // CDN hiển thị ảnh cờ (24x18)
    const flagUrl = `https://flagcdn.com/24x18/${countryCode.toLowerCase()}.png`;

    // Lọc loại bỏ XSS cho thẻ ALT (chỉ giữ lại ký tự a-z)
    const safeCode = String(countryCode).toLowerCase().replace(/[^a-z]/g, "");

    return `
        <img
            src="${flagUrl}"
            alt="${safeCode}"
            class="country-flag"
            onerror="this.style.display='none'"
        >
    `;
}
